return {
  {
    "catppuccin/nvim",
    lazy = false,
    priority = 10000,
    name = "catppuccin",
    enabled = true,
    opts = {
      flavour = "macchiato",
      no_italic = false,
      term_colors = true,
      transparent_background = false,
      show_end_of_buffer = false,
      dim_inactive = {
        enabled = true,
        shade = "dark",
        percentage = 0.40,
      },
      integrations = {
        alpha = true,
        mini = {
          enabled = true,
          indentscope_color = "mauve",
        },
        neotest = true,
        rainbow_delimiters = true,
        overseer = true,
        ufo = true,
        dap = true,
        dap_ui = true,
        cmp = true,
        neogit = true,
        noice = true,
        notify = true,
        window_picker = true,
        lsp_trouble = true,
        which_key = true,
        treesitter = true,
        flash = true,
        gitsigns = true,
        headlines = false,
        markdown = true,
        telescope = {
          enabled = true,
        },
        indent_blankline = {
          enabled = true,
          scope_color = "mauve",
          colored_indent_levels = true,
        },
        lsp_saga = true,
      },
    },
  },
}
