name: Update System
on:
  workflow_dispatch:
    inputs:
      updateFlakes:
        description: Whether or not to update the flakes
        type: boolean
        default: true
        required: true
      commitMessage:
        description: Commit message to use
        type: string
        default: "chore: System update [ci skip]"
        required: true
permissions:
  actions: write
  contents: write
jobs:
  update-system:
    name: Update System
    runs-on: azure
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with:
          name: surface-zen
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true
      - name: Update flakes
        run: nix flake update
        if: ${{ inputs.updateFlakes }}
      - name: Build System configuration
        run: |
          nix build ".#nixosConfigurations.elendil.config.system.build.toplevel"
          cachix push surface-zen result
      - name: Build Home Manager configuration
        run: |
          nix build ".#homeConfigurations.massi@elendil.activationPackage"
          cachix push surface-zen result
      - name: Push flake.lock back to repository
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions[bot]"
          git add flake.lock
          git commit -m "${{ inputs.commitMessage }}"
          git push origin trunk
        if: ${{ inputs.updateFlakes }}
