name: CI
on:
  push:
    branches: ["trunk"]
  pull_request:
jobs:
  check-flake:
    strategy:
      matrix:
        os_version: [azure, macos-15]
    runs-on: ${{ matrix.os_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: nicknovitski/nix-develop@v1
      - run: nix flake check
      - run: nix flake show
  lint-and-format:
    runs-on: azure
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: nicknovitski/nix-develop@v1
      - name: Lint
        run: just lint
      - name: Check format
        run: just check-format
  build-configurations:
    runs-on: ${{ matrix.os_version }}
    strategy:
      matrix:
        os_version: [azure, macos-15]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: surface-zen
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - name: Build Elendil NixOS Configuration
        run: |
          nix build ".#nixosConfigurations.elendil.config.system.build.toplevel"
          cachix push surface-zen result
        if: ${{ matrix.os_version == 'azure' }}
      - name: Build Elendil Home Manager Configuration
        run: |
          nix build ".#homeConfigurations.massi@elendil.activationPackage"
          cachix push surface-zen result
        if: ${{ matrix.os_version == 'azure' }}
      - name: Build WSL NixOS Configuration
        run: |
          nix build ".#nixosConfigurations.aiwendil.config.system.build.toplevel"
          cachix push surface-zen result
        if: ${{ matrix.os_version == 'azure' }}
      - name: Build WSL Home Manager Configuration
        run: |
          nix build ".#homeConfigurations.massi@aiwendil.activationPackage"
          cachix push surface-zen result
        if: ${{ matrix.os_version == 'azure' }}
      - name: Build Darwin Home Manager
        run: |
          nix build ".#homeConfigurations.mgengarelli.activationPackage"
          cachix push surface-zen result
        if: ${{ matrix.os_version == 'macos-15' }}
