name: CI
on:
  push:
    branches: ["trunk"]
  pull_request:
jobs:
  check-flake:
    needs: [lint-and-format]
    strategy:
      matrix:
        os_version: [ubuntu-latest, macos-15]
    runs-on: ${{ matrix.os_version }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: cachix/install-nix-action@v31
      - uses: nicknovitski/nix-develop@v1
      - run: nix flake check
      - run: nix flake show
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: cachix/install-nix-action@v31
      - uses: nicknovitski/nix-develop@v1
      - name: Lint
        run: just lint
      - name: Check format
        run: just check-format
  build-configurations:
    needs: [lint-and-format, check-flake]
    runs-on: ${{ matrix.os_version }}
    strategy:
      matrix:
        os_version: [ubuntu-latest, macos-15]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: surface-zen
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
          tool-cache: true
        if: ${{ matrix.os_version == 'ubuntu-latest' }}
      - name: Build Elendil NixOS Configuration
        run: |
          nix build ".#nixosConfigurations.elendil.config.system.build.toplevel"
          cachix push surface-zen result
        if: ${{ matrix.os_version == 'ubuntu-latest' }}
      - name: Build Elendil Home Manager Configuration
        run: |
          nix build ".#homeConfigurations.massi@elendil.activationPackage"
          cachix push surface-zen result
        if: ${{ matrix.os_version == 'ubuntu-latest' }}
      - name: Clean disk space before building Darwin
        run: |
          sudo rm -rf /usr/local/share/dotnet /usr/share/dotnet /usr/local/lib/android /opt/ghc \
            /Library/Java/JavaVirtualMachines /Users/runner/hostedtoolcache
          df -h
        if: ${{ matrix.os_version == 'macos-15' }}
      - name: Build Darwin System Configuration
        run: |
          nix build ".#darwinConfigurations.work-darwin.config.system.build.toplevel"
          cachix push surface-zen result
        if: ${{ matrix.os_version == 'macos-15' }}
      - name: Build Darwin Home Manager
        run: |
          nix build ".#homeConfigurations.mgengarelli.activationPackage"
          cachix push surface-zen result
        if: ${{ matrix.os_version == 'macos-15' }}
