name: Linters and static analyzers
run-name: Linters for nix 
on: [ push, pull_request ]
jobs:
  Lint-Nix-And-Lua:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Load Nix Configuration
      uses: aldoborrero/use-nix-action@v2
    - name: Lint nix
      run: statix check
    - name: Find nix dead code
      run: deadnix -f
    - name: Check Lua files
      uses: nebularg/actions-luacheck@v1
      with:
        files: ./home/modules/neovim/files

