name: Update System
on:
  workflow_dispatch:
    inputs:
      commitMessage:
        description: Commit message to use
        type: string
        default: "chore: system update"
        required: true
jobs:
  update-system:
    name: Update System
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v27
      - run: nix flake update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: ${{ inputs.commitMessage }}
          branch: chore/system-update
          base: trunk
          delete-branch: true
          title: System Update
          body: |
            - Update flake.lock
